name: AuctionHouse
main: com.gmail.murkhies.AuctionHouse
version: 0.0.1
commands:
   auction:
      description: Basic command for the plugin to create and use AuctionHouses.
      aliases: [ah]
   auction_configuration:
      description: Basic command for the plugin to configure the zone of a auction.
      aliases: [ahc]
permissions:
    auctioner.start:
        description: Start a new auction.
        default: true
    auctioner.stop:
        description: Stop the current auction.
        default: op